/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (3.0.0-SNAPSHOT).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package com.lxisoft.client.open_lrw.api;

import java.util.Map;
import io.swagger.annotations.*;
import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestHeader;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RequestPart;
import org.springframework.web.context.request.NativeWebRequest;
import org.springframework.web.multipart.MultipartFile;

import javax.validation.Valid;
import javax.validation.constraints.*;
import java.util.List;
import java.util.Map;
import java.util.Optional;
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.SpringCodegen", date = "2019-03-29T12:01:52.955+05:30[Asia/Calcutta]")

@Api(value = "OperationHandler", description = "the OperationHandler API")
public interface OperationHandlerApi {

    @ApiOperation(value = "handle", nickname = "handleUsingGET", notes = "", response = Object.class, tags={ "operation-handler", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "OK", response = Object.class),
        @ApiResponse(code = 401, message = "Unauthorized"),
        @ApiResponse(code = 403, message = "Forbidden"),
        @ApiResponse(code = 404, message = "Not Found") })
    @RequestMapping(value = "/actuator/health",
        produces = "application/json", 
        consumes = "application/json",
        method = RequestMethod.GET)
    ResponseEntity<Object> handleUsingGET(@ApiParam(value = "body"  )  @Valid @RequestBody Map<String, String> requestBody);


    @ApiOperation(value = "handle", nickname = "handleUsingGET1", notes = "", response = Object.class, tags={ "operation-handler", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "OK", response = Object.class),
        @ApiResponse(code = 401, message = "Unauthorized"),
        @ApiResponse(code = 403, message = "Forbidden"),
        @ApiResponse(code = 404, message = "Not Found") })
    @RequestMapping(value = "/actuator/info",
        produces = "application/json", 
        consumes = "application/json",
        method = RequestMethod.GET)
    ResponseEntity<Object> handleUsingGET1(@ApiParam(value = "body"  )  @Valid @RequestBody Map<String, String> requestBody);

}
