/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (3.0.0-SNAPSHOT).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package com.lxisoft.client.open_lrw.api;

import com.lxisoft.client.open_lrw.model.CollectionMongoRisk;
import com.lxisoft.client.open_lrw.model.MongoRisk;
import io.swagger.annotations.*;
import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestHeader;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RequestPart;
import org.springframework.web.context.request.NativeWebRequest;
import org.springframework.web.multipart.MultipartFile;

import javax.validation.Valid;
import javax.validation.constraints.*;
import java.util.List;
import java.util.Map;
import java.util.Optional;
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.SpringCodegen", date = "2019-03-29T12:01:52.955+05:30[Asia/Calcutta]")

@Api(value = "RiskController", description = "the RiskController API")
public interface RiskControllerApi {

    @ApiOperation(value = "getClassUser", nickname = "getClassUserUsingGET", notes = "", response = CollectionMongoRisk.class, tags={ "risk-controller", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "OK", response = CollectionMongoRisk.class),
        @ApiResponse(code = 401, message = "Unauthorized"),
        @ApiResponse(code = 403, message = "Forbidden"),
        @ApiResponse(code = 404, message = "Not Found") })
    @RequestMapping(value = "/api/risks/classes/{classSourcedId}/users/{userSourcedId}",
        produces = "*/*", 
        method = RequestMethod.GET)
    ResponseEntity<CollectionMongoRisk> getClassUserUsingGET(@ApiParam(value = "classSourcedId",required=true) @PathVariable("classSourcedId") String classSourcedId,@ApiParam(value = "userSourcedId",required=true) @PathVariable("userSourcedId") String userSourcedId,@ApiParam(value = "") @Valid @RequestParam(value = "details", required = false) Object details,@ApiParam(value = "") @Valid @RequestParam(value = "authenticated", required = false) Boolean authenticated,@ApiParam(value = "date") @Valid @RequestParam(value = "date", required = false) String date);


    @ApiOperation(value = "getLatestRiskScoresForClass", nickname = "getLatestRiskScoresForClassUsingGET", notes = "", response = MongoRisk.class, responseContainer = "List", tags={ "risk-controller", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "OK", response = MongoRisk.class, responseContainer = "List"),
        @ApiResponse(code = 401, message = "Unauthorized"),
        @ApiResponse(code = 403, message = "Forbidden"),
        @ApiResponse(code = 404, message = "Not Found") })
    @RequestMapping(value = "/api/risks/{classSourcedId}/latest",
        produces = "*/*", 
        method = RequestMethod.GET)
    ResponseEntity<List<MongoRisk>> getLatestRiskScoresForClassUsingGET(@ApiParam(value = "classSourcedId",required=true) @PathVariable("classSourcedId") String classSourcedId,@ApiParam(value = "") @Valid @RequestParam(value = "details", required = false) Object details,@ApiParam(value = "") @Valid @RequestParam(value = "authenticated", required = false) Boolean authenticated);


    @ApiOperation(value = "post", nickname = "postUsingPOST3", notes = "", response = Object.class, tags={ "risk-controller", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "OK", response = Object.class),
        @ApiResponse(code = 201, message = "Created"),
        @ApiResponse(code = 401, message = "Unauthorized"),
        @ApiResponse(code = 403, message = "Forbidden"),
        @ApiResponse(code = 404, message = "Not Found") })
    @RequestMapping(value = "/api/risks",
        produces = "*/*", 
        consumes = "application/json",
        method = RequestMethod.POST)
    ResponseEntity<Object> postUsingPOST3(@ApiParam(value = "mongoRisk" ,required=true )  @Valid @RequestBody MongoRisk mongoRisk,@ApiParam(value = "") @Valid @RequestParam(value = "details", required = false) Object details,@ApiParam(value = "") @Valid @RequestParam(value = "authenticated", required = false) Boolean authenticated,@ApiParam(value = "check") @Valid @RequestParam(value = "check", required = false) Boolean check);

}
