/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (3.0.0-SNAPSHOT).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package com.lxisoft.client.open_lrw.api;

import com.lxisoft.client.open_lrw.model.CollectionTenant;
import com.lxisoft.client.open_lrw.model.Tenant;
import io.swagger.annotations.*;
import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestHeader;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RequestPart;
import org.springframework.web.context.request.NativeWebRequest;
import org.springframework.web.multipart.MultipartFile;

import javax.validation.Valid;
import javax.validation.constraints.*;
import java.util.List;
import java.util.Map;
import java.util.Optional;
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.SpringCodegen", date = "2019-03-29T12:01:52.955+05:30[Asia/Calcutta]")

@Api(value = "TenantController", description = "the TenantController API")
public interface TenantControllerApi {

    @ApiOperation(value = "getOne", nickname = "getOneUsingGET1", notes = "", response = Tenant.class, tags={ "tenant-controller", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "OK", response = Tenant.class),
        @ApiResponse(code = 401, message = "Unauthorized"),
        @ApiResponse(code = 403, message = "Forbidden"),
        @ApiResponse(code = 404, message = "Not Found") })
    @RequestMapping(value = "/api/tenants/{tenantId}",
        produces = "*/*", 
        method = RequestMethod.GET)
    ResponseEntity<Tenant> getOneUsingGET1(@ApiParam(value = "tenantId",required=true) @PathVariable("tenantId") String tenantId);


    @ApiOperation(value = "get", nickname = "getUsingGET", notes = "", response = CollectionTenant.class, tags={ "tenant-controller", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "OK", response = CollectionTenant.class),
        @ApiResponse(code = 401, message = "Unauthorized"),
        @ApiResponse(code = 403, message = "Forbidden"),
        @ApiResponse(code = 404, message = "Not Found") })
    @RequestMapping(value = "/api/tenants",
        produces = "*/*", 
        method = RequestMethod.GET)
    ResponseEntity<CollectionTenant> getUsingGET();


    @ApiOperation(value = "post", nickname = "postUsingPOST4", notes = "", response = Object.class, tags={ "tenant-controller", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "OK", response = Object.class),
        @ApiResponse(code = 201, message = "Created"),
        @ApiResponse(code = 401, message = "Unauthorized"),
        @ApiResponse(code = 403, message = "Forbidden"),
        @ApiResponse(code = 404, message = "Not Found") })
    @RequestMapping(value = "/api/tenants",
        produces = "*/*", 
        consumes = "application/json",
        method = RequestMethod.POST)
    ResponseEntity<Object> postUsingPOST4(@ApiParam(value = "tenant" ,required=true )  @Valid @RequestBody Tenant tenant);

}
