/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (3.0.0-SNAPSHOT).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package com.lxisoft.client.open_lrw.api;

import java.util.Map;

import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;

import io.swagger.annotations.Api;
import io.swagger.annotations.ApiOperation;
import io.swagger.annotations.ApiResponse;
import io.swagger.annotations.ApiResponses;

@javax.annotation.Generated(value = "org.openapitools.codegen.languages.SpringCodegen", date = "2019-03-29T12:01:52.955+05:30[Asia/Calcutta]")

@Api(value = "WebMvcEndpointHandlerMapping", description = "the WebMvcEndpointHandlerMapping API")
public interface WebMvcEndpointHandlerMappingApi {

	@ApiOperation(value = "links", nickname = "linksUsingGET", notes = "", response = Map.class, responseContainer = "Map", tags = {
			"web-mvc-endpoint-handler-mapping", })
	@ApiResponses(value = { @ApiResponse(code = 200, message = "OK", response = Map.class, responseContainer = "Map"),
			@ApiResponse(code = 401, message = "Unauthorized"), @ApiResponse(code = 403, message = "Forbidden"),
			@ApiResponse(code = 404, message = "Not Found") })
	@RequestMapping(value = "/actuator", produces = "application/json", method = RequestMethod.GET)
	ResponseEntity<Map<String, Map<String, String>>> linksUsingGET();

}
