/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (3.0.0-SNAPSHOT).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package com.lxisoft.client.xapi_launch_karma_app.api;

import com.lxisoft.client.xapi_launch_karma_app.model.ContentRecordDTO;
import io.swagger.annotations.*;
import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestHeader;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RequestPart;
import org.springframework.web.context.request.NativeWebRequest;
import org.springframework.web.multipart.MultipartFile;

import javax.validation.Valid;
import javax.validation.constraints.*;
import java.util.List;
import java.util.Map;
import java.util.Optional;
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.SpringCodegen", date = "2019-03-25T12:34:05.544+05:30[Asia/Calcutta]")

@Api(value = "ContentRecordResource", description = "the ContentRecordResource API")
public interface ContentRecordResourceApi {

    @ApiOperation(value = "createContentRecord", nickname = "createContentRecordUsingPOST", notes = "", response = ContentRecordDTO.class, tags={ "content-record-resource", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "OK", response = ContentRecordDTO.class),
        @ApiResponse(code = 201, message = "Created"),
        @ApiResponse(code = 401, message = "Unauthorized"),
        @ApiResponse(code = 403, message = "Forbidden"),
        @ApiResponse(code = 404, message = "Not Found") })
    @RequestMapping(value = "/api/content-records",
        produces = "*/*", 
        consumes = "application/json",
        method = RequestMethod.POST)
    ResponseEntity<ContentRecordDTO> createContentRecordUsingPOST(@ApiParam(value = "contentRecordDTO" ,required=true )  @Valid @RequestBody ContentRecordDTO contentRecordDTO);


    @ApiOperation(value = "deleteContentRecord", nickname = "deleteContentRecordUsingDELETE", notes = "", tags={ "content-record-resource", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "OK"),
        @ApiResponse(code = 204, message = "No Content"),
        @ApiResponse(code = 401, message = "Unauthorized"),
        @ApiResponse(code = 403, message = "Forbidden") })
    @RequestMapping(value = "/api/content-records/{id}",
        method = RequestMethod.DELETE)
    ResponseEntity<Void> deleteContentRecordUsingDELETE(@ApiParam(value = "id",required=true) @PathVariable("id") String id);


    @ApiOperation(value = "getAllContentRecords", nickname = "getAllContentRecordsUsingGET", notes = "", response = ContentRecordDTO.class, responseContainer = "List", tags={ "content-record-resource", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "OK", response = ContentRecordDTO.class, responseContainer = "List"),
        @ApiResponse(code = 401, message = "Unauthorized"),
        @ApiResponse(code = 403, message = "Forbidden"),
        @ApiResponse(code = 404, message = "Not Found") })
    @RequestMapping(value = "/api/content-records",
        produces = "*/*", 
        method = RequestMethod.GET)
    ResponseEntity<List<ContentRecordDTO>> getAllContentRecordsUsingGET(@ApiParam(value = "") @Valid @RequestParam(value = "offset", required = false) Long offset,@ApiParam(value = "Page number of the requested page") @Valid @RequestParam(value = "page", required = false) Integer page,@ApiParam(value = "") @Valid @RequestParam(value = "pageNumber", required = false) Integer pageNumber,@ApiParam(value = "") @Valid @RequestParam(value = "pageSize", required = false) Integer pageSize,@ApiParam(value = "") @Valid @RequestParam(value = "paged", required = false) Boolean paged,@ApiParam(value = "Size of a page") @Valid @RequestParam(value = "size", required = false) Integer size,@ApiParam(value = "Sorting criteria in the format: property(,asc|desc). Default sort order is ascending. Multiple sort criteria are supported.") @Valid @RequestParam(value = "sort", required = false) List<String> sort,@ApiParam(value = "") @Valid @RequestParam(value = "sort.sorted", required = false) Boolean sortSorted,@ApiParam(value = "") @Valid @RequestParam(value = "sort.unsorted", required = false) Boolean sortUnsorted,@ApiParam(value = "") @Valid @RequestParam(value = "unpaged", required = false) Boolean unpaged);


    @ApiOperation(value = "getContentRecord", nickname = "getContentRecordUsingGET", notes = "", response = ContentRecordDTO.class, tags={ "content-record-resource", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "OK", response = ContentRecordDTO.class),
        @ApiResponse(code = 401, message = "Unauthorized"),
        @ApiResponse(code = 403, message = "Forbidden"),
        @ApiResponse(code = 404, message = "Not Found") })
    @RequestMapping(value = "/api/content-records/{id}",
        produces = "*/*", 
        method = RequestMethod.GET)
    ResponseEntity<ContentRecordDTO> getContentRecordUsingGET(@ApiParam(value = "id",required=true) @PathVariable("id") String id);


    @ApiOperation(value = "updateContentRecord", nickname = "updateContentRecordUsingPUT", notes = "", response = ContentRecordDTO.class, tags={ "content-record-resource", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "OK", response = ContentRecordDTO.class),
        @ApiResponse(code = 201, message = "Created"),
        @ApiResponse(code = 401, message = "Unauthorized"),
        @ApiResponse(code = 403, message = "Forbidden"),
        @ApiResponse(code = 404, message = "Not Found") })
    @RequestMapping(value = "/api/content-records",
        produces = "*/*", 
        consumes = "application/json",
        method = RequestMethod.PUT)
    ResponseEntity<ContentRecordDTO> updateContentRecordUsingPUT(@ApiParam(value = "contentRecordDTO" ,required=true )  @Valid @RequestBody ContentRecordDTO contentRecordDTO);

}
